# Generated by Django 6.0.4 on 2026-04-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Savings', models.FloatField()),
                ('FireExtinguisher', models.FloatField()),
                ('Splurge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Amount', models.FloatField()),
                ('Category', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
    ]
