# Generated by Django 6.0.4 on 2026-04-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='Everyday',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
